### ISSUE TITLE
How to config?

### ISSUE THREAD

**Issue by Magic-Hole** [tingirifistik/HourBooster#9]
Please help me 
![image](https://github.com/tingirifistik/Steam-HourBooster/assets/76911277/378f5f25-c9bc-497e-a70b-407a6a905a10)
I have only the token tg bot

**Comment by tingirifistik** [comment]
Remove getenv("token") from the token=getenv("token") part and directly assign your token value(str)
e.g. token = "telegramToken" 

After, type /start on telegram to start bot

**Comment by Magic-Hole** [comment]
And games the ids must be how : 
id,id ? id, id ? id , id ?

**Comment by tingirifistik** [comment]
must be: 
id,id,id
